version: '3.4'

services:
  nodedocker:
    image: nodedocker
    command: npm start
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo:6.0.4
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: 
